### ISSUE TITLE
No provider "SQLite" installed

### ISSUE THREAD

**Issue by dereke** [Alecaddd/sequeler#111]
I've compiled the project from git master.
When I try to open a SQLite file I get this error:

![image](https://user-images.githubusercontent.com/144922/39196135-4d382f54-47d9-11e8-9024-df6b840d8ede.png)

What have I done wrong?

**Comment by Alecaddd** [comment]
Try running these commands in your terminal:
`sudo apt-get install sqlite3 libsqlite3-dev`

**Comment by dereke** [comment]
oh I didn't realise there was a flatpak - it works great thank you!

**Comment by captn3m0** [comment]
The fedora package depends on `libgda-sqlite`  and not `libgda5-sqlite`.  Reported upstream at https://bugzilla.redhat.com/show_bug.cgi?id=2295154

**Comment by musicinmybrain** [comment]
> The fedora package depends on `libgda-sqlite` and not `libgda5-sqlite`. Reported upstream at https://bugzilla.redhat.com/show_bug.cgi?id=2295154

Thanks for reporting this! In Fedora 37, `libgda` was updated from 5.x to 6.x, and a new `libgda5` compat package was introduced. The build dependency, of the form `pkgconfig(libgda-5.0)`, still finds the correct library (see: https://github.com/Alecaddd/sequeler/issues/376), but the weak dependencies on the supported backends have been broken in Fedora 37 and later since they now install GDA 6.x providers instead of GDA 5.x providers. I have issued updates for all releases to correct this:

- Fedora Rawhide: [FEDORA-2024-4de2c0451e](https://bodhi.fedoraproject.org/updates/FEDORA-2024-4de2c0451e)
- Fedora 40: [FEDORA-2024-f9ecdc0278](https://bodhi.fedoraproject.org/updates/FEDORA-2024-f9ecdc0278)
- Fedora 39: [FEDORA-2024-cd3498f8aa](https://bodhi.fedoraproject.org/updates/FEDORA-2024-cd3498f8aa)

The Rawhide update will appear in the next successful compose; the others will be in updates-testing for about a week before appearing in the stable updates repositories. If Fedora users have any further issues with backends/providers, please feel free to comment in https://bugzilla.redhat.com/show_bug.cgi?id=2295154.

In general, please feel free to file downstream issues at https://bugzilla.redhat.com/ for anything you suspect could be Fedora-specific. These are helpful because I don’t closely monitor the issues on this GitHub project.
