### ISSUE TITLE
Screenshots in appdata shouldn't contain shadows

### ISSUE THREAD

**Issue by Alexander-Wilms** [Alecaddd/sequeler#209]
According to the [spec](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html), the screenshots shouldn't contain window shadows.

This should look better in software centers as well.

**Comment by Alecaddd** [comment]
Hi, thanks for using Sequeler and for the heads up.
I'm using drop shadows because this app is first and foremost an elementary OS app, and screenshots are representative of how it looks with the window decoration of that distro.
I don't see any issue since the app should available only in the elementary OS AppCenter and FlatHub, which both accept and kinda recommend having drop shadows.
Thanks again.
