### ISSUE TITLE
No "About" box

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#228]
There are no "Help" or "About" menu items, and no way to get the current version number (for example for reporting bugs). Running with the "--version" option doesn't work either.

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by Alecaddd** [comment]
Sequeler doesn't have an About widget by choice because it doesn't need one.
The 2 currently available and supported distribution packages are FlatPak and via elementary OS AppCenter. Both these distributions come with versioning built-in.
I'm not the maintainer of the AUR package, so, I'm sorry but I don't know how to help you.
