### ISSUE TITLE
"Query" tab should not be separate

### ISSUE THREAD

**Issue by svartrev** [Alecaddd/sequeler#232]
When logged in to a database, there are four tabs available: "Structure", "Content", "Relations" and "Query". The first three tabs change content depending on which table is selected, but the Query tab doesn't, and should be visually separate from the other three.

This is only a minor point, but in terms of UI design, the Query tab functions differently to the other tabs, and should be visually different too.

I'm running Sequeler on Arch Linux, installed from the AUR.
In my build folder this file was created: sequeler-git-r619.a3afaa5-1-x86_64.pkg.tar.xz
As far as I can tell, that means I'm running the latest version of Sequeler.

**Comment by Alecaddd** [comment]
I disagree with this opinion.
The Query tab is another gateway to visualizing the content of the database. The Query tab only differs by the fact that allows the user to write custom queries to filter content and trigger specific commands.
It wouldn't make sense separate it from the rest since it uses the same content rendering UI and it offers the same purpose of the other 3 tabs, which is accessing the data.
