### ISSUE TITLE
No Provider PostgreSQL installed

### ISSUE THREAD

**Issue by hdijkema** [Alecaddd/sequeler#378]
Installing sequeler on Ubuntu 22.04...

I get 'no provider postgresql' installed although I installed libgda-5.0:

`i   libgda-5.0-postgres                                          - PostgreSQL provider for libgda database abstraction library   `

What could be the problem?

**Comment by dannluciano** [comment]
I have the same issue

**Comment by dannluciano** [comment]
I can fix the issue after install ```libgda-5.0-postgres``` and ```Sequeler``` via apt-get.

**Comment by hdijkema** [comment]
I installed libdga-5.0-postgres and that didn’t help.

Op zo 31 jul. 2022 om 18:18 schreef Dann Luciano ***@***.***>

**Comment by hdijkema** [comment]
However, after some days, probably after a reboot of my system sequeler suddenly starts to work with postgresql. 
Maybe it's better to make sequeler dependent on the libdga modules to start with.

**Comment by mickeymond** [comment]
Is there an actual working fix for this or should I just keep my figures crossed?
PS: I am using Fedora 37 Workstation.

**Comment by vsile** [comment]
I have the same issue on Fedora 37.
libgda-postgres-1:6.0.0-1.fc37.x86_64 is installed. But the application returns an error: No provider PosrgreSQL installed.

**Comment by jberli** [comment]
> However, after some days, probably after a reboot of my system sequeler suddenly starts to work with postgresql.
> Maybe it's better to make sequeler dependent on the libdga modules to start with.

I can confirm that on Debian testing, I had to install libdga-5.0-postgres and reboot my system for it to work.

**Comment by thierry-carron** [comment]
Hi I have the same message error. psql is running
psql -V
psql (PostgreSQL) 15.5 (Debian 15.5-0+deb12u1)
bug ?

**Comment by musicinmybrain** [comment]
This was just reported [downstream in Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2295154). In Fedora 37, `libgda` was updated from 5.x to 6.x, and a new `libgda5` compat package was introduced. The build dependency, of the form `pkgconfig(libgda-5.0)`, still finds the correct library (see: https://github.com/Alecaddd/sequeler/issues/376), but the weak dependencies on the supported backends have been broken in Fedora 37 and later since they now install GDA 6.x providers instead of GDA 5.x providers. I have issued updates for all releases to correct this:

- Fedora Rawhide: [FEDORA-2024-4de2c0451e](https://bodhi.fedoraproject.org/updates/FEDORA-2024-4de2c0451e)
- Fedora 40: [FEDORA-2024-f9ecdc0278](https://bodhi.fedoraproject.org/updates/FEDORA-2024-f9ecdc0278)
- Fedora 39: [FEDORA-2024-cd3498f8aa](https://bodhi.fedoraproject.org/updates/FEDORA-2024-cd3498f8aa)

The Rawhide update will appear in the next successful compose; the others will be in updates-testing for about a week before appearing in the stable updates repositories. If Fedora users have any further issues with backends/providers, please feel free to comment in https://bugzilla.redhat.com/show_bug.cgi?id=2295154.

In general, please feel free to file downstream issues at https://bugzilla.redhat.com/ for anything you suspect could be Fedora-specific. These are helpful because I don’t closely monitor the issues on this GitHub project.
