### ISSUE TITLE
SQL Lite path breaks

### ISSUE THREAD

**Issue by rasmus91** [Alecaddd/sequeler#72]
Hey.

Currently using your fantastic app with sqlite, just one problem. When i Insert a path and save the connection it works fine. But suddenly, it interchanged all slashes in a path with: "%25252f" and so claiming the path was incorrect. 

It seems to let me connect to the DB once, then changing the slash symbol in the path. Very annoying.

**Comment by Alecaddd** [comment]
Mhhh, that's weird, it shouldn't happen.
That's the encoded path necessary for the `LibGDA` to connect to your database, but the encoding is done only during the call to open the database, it shouldn't update your stored variable.
I can't recreate the issue, so that means something is going on randomly, which is not good >_>

Thanks for the report and sorry for annoyance.
